applications:
- name: revampd-api
  memory: 64M
  path: ../../src
  command: ./bin/revampd
  stack: cflinuxfs3
  buildpacks:
  - go_buildpack
  env:
    GOVERSION: go1.12
    GOPACKAGENAME: github.com/18F/revampd
